services:
  sehaty-plus:
    image: ${DOCKER_REGISTRY-}sehatyplus
    container_name: sehaty-plus.api
    build:
      context: .
      dockerfile: Sehaty-Plus/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ConnectionStrings__Redis=sehaty-plus.redis:6379
    networks:
      - sehaty-net
    depends_on:
      - sehaty-plus.database
      - sehaty-plus.redis

  sehaty-plus.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sehaty-plus.database
    environment:
      SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - sehaty-net

  sehaty-plus.redis:
    image: redis:latest
    container_name: sehaty-plus.redis
    ports:
      - "6379:6379"
    networks:
      - sehaty-net
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: sehaty-plus.redisinsight
    ports:
      - "8012:8011"
    networks:
      - sehaty-net

networks:
  sehaty-net: